name: Push Image to Aliyun
on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun
        # 这里的域 名 crpi-lldf5xbqet88oliy.cn-hangzhou.personal.cr.aliyuncs.com 必须和 tag/push 保持一致
        run: docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} crpi-lldf5xbqet88oliy.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Pull and Retag
        run: |
          # 1. 从 GitHub 拉取原版镜像
          docker pull ghcr.io/puppeteer/puppeteer:latest
          
          # 2. 改名：地址/命名空间/仓库名:标签
          # 你的命名空间是 moonshift，仓库名是 openclaw
          docker tag ghcr.io/puppeteer/puppeteer:latest crpi-lldf5xbqet88oliy.cn-hangzhou.personal.cr.aliyuncs.com/moonshift/puppeteer:latest

      - name: Push to Aliyun
        # 3. 推送到阿里云，这个过程是由 GitHub 服务器完成的
        run: docker push crpi-lldf5xbqet88oliy.cn-hangzhou.personal.cr.aliyuncs.com/moonshift/puppeteer:latest
